import { createFileRoute, Link } from "@tanstack/react-router";
import editorialHero from "@/assets/rakzs-commercial-fashion.jpg";
import { PageHero } from "@/components/rakzs/PageHero";
import { ServiceCard } from "@/components/rakzs/ServiceCard";
import { SectionHeader } from "@/components/rakzs/SectionHeader";
import { Button } from "@/components/ui/button";
import { services } from "@/data/site";

export const Route=createFileRoute("/services")({head:()=>({meta:[{title:"Photography, Videography & Editing Services — RAKZS STUDIO"},{name:"description",content:"Explore photography, videography, photo editing, and video editing services with custom quotes."},{property:"og:title",content:"Creative Services — RAKZS STUDIO"},{property:"og:description",content:"Photography, films, retouching, and editing shaped into one consistent visual story."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:ServicesPage});
function ServicesPage(){return <><PageHero eyebrow="Services" title="Every part of the story, crafted under one roof." description="Photography, film, retouching, and editing shaped around your occasion, audience, and intended feeling." image={editorialHero}/><section className="section-band"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionHeader eyebrow="Creative Services" title="Tailored coverage. Considered finishing." description="Every project is scoped individually. Request a custom quote for your date and deliverables."/><div className="grid gap-7 lg:grid-cols-2">{services.map(service=><ServiceCard key={service.slug} service={service}/>)}</div></div></section><section className="section-band bg-card"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[1fr_0.8fr] lg:px-8"><div><p className="section-kicker">Complete Storytelling</p><h2 className="mt-4 font-display text-5xl md:text-6xl">Photography + Videography + Editing</h2><p className="mt-6 max-w-2xl leading-8 text-muted-foreground">Bring the full production together with one visual direction—from planning and capture through careful retouching, cinematic grading, albums, films, and social-ready edits.</p></div><div className="self-center border-l border-primary pl-8"><p className="font-display text-3xl">Request a Custom Quote</p><p className="mt-3 text-sm leading-7 text-muted-foreground">Scope depends on your date, location, coverage hours, team requirements, and final delivery formats.</p><Button asChild variant="gold" className="mt-7"><Link to="/contact" search={{service:"Photography + Videography + Editing",event:undefined}}>Enquire Now</Link></Button></div></div></section></>}
